---
title: "Computing for the Social Sciences"
format:
  html:
    toc: false
    theme: cosmo
---

### Course Information Fall 2026

<div class="my-4"></div>

**Lectures**: Mondays & Wednesdays, 11:30–1:20 PM, 1155 Building E. 60th St, Room 295 

<div class="my-4"></div>

**Teaching Team**:  

- Instructor: Sabrina Nardin (she/her) – [nardin@uchicago.edu](mailto:nardin@uchicago.edu)  
- TA: Xulan Jiang (he/him) – [xulanj@uchicago.edu](mailto:xulanj@uchicago.edu)
- TA: Mirana Zhang (she/her) – [miranazhang@uchicago.edu](mailto:miranazhang@uchicago.edu)

<div class="my-4"></div>

**Office Hours**:

| Day & Time                        | Type                                                                 | Location              | Person |
|-----------------------------------|----------------------------------------------------------------------|-----------------------|------------|
| Mon 11:00–11:30 AM (before class) | *Drop-in*                                                            | Our classroom         | Mirana     |
| Mon 1:20–1:30 PM (after class)    | *Drop-in*                                                            | Our classroom         | Sabrina    |
| Mon 1:30–3:00 PM                  | [*By appointment*](https://calendar.app.google/PTagCLFrarGsxZ2S9)    | 1155 Bldg, Room TBD   | Mirana     |
| Tue 9:00–11:00 AM                 | [*By appointment*](https://calendar.app.google/xtDH9Pnf8yJtP9jg6)    | 1155 Bldg, Room 221A  | Sabrina    |
| Wed 11:00–11:30 AM (before class) | *Drop-in*                                                            | Our classroom         | Xulan       |
| Wed 1:20–1:30 PM (after class)    | *Drop-in*                                                           | Our classroom         | Sabrina   |
| Thu 3:30–5:00 PM                  | [*By appointment*](https://calendar.app.google/kfQRpzbvA2E8MUtk6)    | 1155 Bldg, Room TBD   | Xulan     |

<div class="my-4"></div>

**Quick Links**:  

- [R Workbench](https://macss-r.uchicago.edu/)  
- [Canvas](https://canvas.uchicago.edu/courses/75075)  
- [Ed Discussion](https://edstem.org/us/courses/107272/discussion/8310890)


<!--
R course to check https://stat-37815-au24.ryanmcshane.com/
-->
