---
title: "Computing for the Social Sciences"
format:
  html:
    toc: true
    theme: cosmo
engine: knitr
execute:
  echo: false
---

<!-- 
<div class="my-4"></div>
*Last updated:* `r format(Sys.Date(), "%B %d, %Y")` 
-->

## Course Syllabus Fall 2026

*Last updated: September 27, 2026*

Welcome to "Computing for the Social Sciences"!

For course information (Emails, Office Hours, etc.) see [Home](index.qmd).

This is an applied course for social scientists with little-to-no programming experience who wish to harness growing digital and computational resources. The focus is on learning the basics of programming in R and generating reproducible research. Topics include coding concepts (e.g., data structures, control structures, etc.), data visualization, data wrangling, web scraping, version control software, exploratory data analysis, and more. Students will leave the course with basic programming skills for the social sciences and the ability to adapt and expand these skills as they encounter new questions, methods, and data beyond the course.

Requirements: No prior experience with R is required, though it’s helpful to have completed a course involving a programming language (e.g., Python, Stata, SPSS, or others) in some capacity. If you're unsure or have had informal exposure to programming, please email the instructor to see if the course is a good fit.

Note: MACS 30500 is cross-listed with CHDV 30511/ENST 20550/MACS 20500/MAPS 30500/PLSC 30235/PSYC 30510/SOCI 20278/SOCI 40176/SOSC 26032


## Learning Objectives

By the end of the course, students will be able to:

- Construct and execute basic programs in R using programming techniques
- Use the most important tidyverse libraries
- Search for external libraries to enhance R's base functions
- Apply Git and GitHub workflows for version control within RStudio
- Create and edit R Markdown documents to produce reproducible reports and presentations
- Import data from various sources
- Clean and transform raw data
- Transform data into a tidy format
- Visualize and interpret data using descriptive methods
- Manipulate strings and dates
- Scrape websites to collect data


## Materials, Schedule, and Content

The main textbook for this course is the 2nd edition of [R for Data Science](https://r4ds.hadley.nz/) by Garrett Grolemund and Hadley Wickham. The book is freely accessible online. All course materials and assignments will be available on the course website. Consulting the textbook and reviewing the in-class material is required. 

See [Course Content and Schedule](lectures/index.qmd) for information on every lecture. Schedule and Content might be subject to change, but if changes occur students will be promptly informed.


## Course Expectations

**Intended Audience**  
This course is for UChicago students who want to use R as a tool for analyzing data, typically in the social sciences. It is not a computer science course, but an introduction to programming for research: many students who have taken it in the past were looking to build skills they could apply to their own research projects. If you have never programmed before, expect a new way of thinking: the course will be challenging but rewarding if you commit to the course for the full quarter.  
<!-- put students profiles in slides 1 -->

**Own Your Learning Journey**  
Each class has readings and class materials (slides and code) posted on this website. Come prepared with questions you’d like to raise: class time mixes lecture and practice, and questions are strongly encouraged. Regular attendance at lectures is expected. Please inform the instructor in advance if you must miss a class. Assignments may feel challenging, but they are carefully designed and tested to be achievable using only course materials (see our course-specific AI policies below). Start early, keep up with deadlines, and reach out if you need help along the way!

**Shared Expectations**  
This course works best when our instructor–student relationship is grounded in mutual trust and a shared commitment to learning.
You can trust that I have designed the course and its policies thoughtfully, with the goal of supporting your learning and helping you build a strong foundation in R. In turn, I trust that you will engage seriously with the material and take responsibility for your work. You can also expect transparency from me and the TAs about course policies, grading, and the reasoning behind our approach.


## Assessment

### Types of Assessment

Student learning in this course will be assessed as follows:

| What                               | Points  | Grading Method |
|------------------------------------|---------|----------------|
| Assignment 1                       | 4       | Pass/Fail      |
| Assignment 2                       | 15      | Points-Based   |
| Assignment 3                       | 15      | Points-Based   |
| Assignment 4                       | 15      | Points-Based   |
| Assignment 5 (Final Project)       | 15      | Points-Based   |
| In-Class Short Exam 1              | 18      | Points-Based   |
| In-Class Short Exam 2              | 18      | Points-Based   |
| *Optional Oral Exam*             | Grade Adj.| Points-Based   |
| **Total**                          | **100** |                |

The course includes the following types of assessments:

- **Take-Home Assignments:** The course includes five required take-home assignments covering the main material taught in class; the fifth assignment serves as the final project and gives you the opportunity to work on a topic of your own interest.

- **In-Class Exams:** The course includes two in-class exams, each covering a different portion of the course. Exams include multiple-choice and open-ended questions. They are *closed-book*: no notes, textbooks, phones, or other materials are permitted. Only the exam and your computer may be used. Most lectures will include opportunities to review relevant material, practice the exam format, and ask questions.

- **Oral Exam (optional):** During Week 10, you may sign up for an optional oral exam with the instructor to improve your grade one of Assignments 2–4 or one in-class exam of your choice. The oral exam assesses both the selected assessment and broader course content mastery, providing an additional opportunity to demonstrate your understanding of course material after completing the original assessment. *Specific eligibility and scoring rules will apply to the oral exam:* see the Oral Exam page (will be posted during the quarter) for detailed guidelines, including eligibility, format, scoring rules, examples, sign-up instructions, and the rubric.


<!-- ORAL EXAM DETAILS AS OF 9/26/26 SEE ALSO ORAL-HOME PAGE

- The oral exam is optional and allows you to improve your grade on **one of the four regular take-home assignments** or **one in-class exam**. The final project is not eligible. You may complete the oral exam only once.

- It consists of a **15–20 minute, one-on-one conversation** with the instructor during Week 10. You may be asked to discuss code from any take-home assignment, explain answers from either exam, and connect your work to course materials. The oral exam is intended to assess overall course mastery, but **at least half of the oral will relate directly to the assessment you selected**.

- The oral exam can improve the selected assessment by up to **10 percentage points**. Your oral exam percentage divided by 10 determines the number of percentage points added. For example, an 80% oral exam score adds 8 percentage points, while a 100% adds 10.

- A score of **70% or higher on the oral exam is required** for any adjustment. This threshold is based on the unrounded oral exam score. The oral exam cannot lower your original grade.

- Because exams and assignments carry different point values, the maximum raw-point increase differs accordingly: up to **+2 points** on a 20-point exam and **+1.4 points** on a 14-point take-home assignment. The number and depth of questions may vary slightly depending on the type of assessment selected. For example, a **15/20 (75%)** on Exam 1 combined with an **80% oral exam score** becomes **16.6/20 (83%)**. An **11/14 (78.6%)** on an assignment combined with a **100% oral exam score** becomes **12.4/14 (88.6%)**.

- The adjusted assessment grade cannot exceed **100%**, and unused points do not count as extra credit.

- When you sign up, **you must indicate which assignment or exam you want the adjustment applied to**. Please choose carefully, as your selected assessment cannot be changed after the oral exam takes place. You may also be asked to submit a brief preparation note identifying the main concepts, questions, or mistakes from that assessment that you plan to revisit. Note that the oral exam will still assess broader course mastery and may include questions related to other assignments or exams.

- You will be evaluated using a rubric, and the general topics and types of questions will be shared in advance. Approved accommodations apply to the oral exam.

- Because the oral exam is optional and scheduled during Week 10, missed oral exams will be handled according to the course’s regular absence and make-up policies.

-->

### Rubric for Take-Home Assignments

Grades are part of most educational systems, but a score reflects your work on one assignment, not your overall worth or ability. To make grading as transparent as possible, I use rubrics for all graded assessments that require human assessment, such as take-home assignments and the oral exam. Pass/fail assignments will not have rubrics.

Specifically, all take-home assignments are evaluated using the following rubric, with performance rate as as *Excellent* (A+/A), *Very Good* (A-), *Good* (B+/B), *Needs Improvement* (C), or *Not Sufficient* (below C) across five categories, weighted as follows:  

- **Coding Strategy (20%)**:  
  - the logic of your code (how it solves the problem),  
  - correctness (does it work?),  
  - sophistication (depth of solution),  
  - use of course tools/techniques (e.g., conditionals, functions, tidyverse, etc.),  
  - efficiency (avoiding unnecessary repetition).  

- **Presentation and Explanation (20%)**:   
  - effectiveness of visualizations, tables, or summaries,  
  - clarity of conceptual choices in presenting data,  
  - your ability to interpret results,  
  - use of Markdown syntax.    

- **Achievement (20%)**:  
  - your mastery of the required concepts/tools,  
  - creativity and initiative,  
  - ability to go beyond minimum requirements,  
  - note that *Excellent* in this category indicates truly outstanding work.  

- **Reproducibility (20%)**:  
  - compliance with course conventions (repo access, required files submitted),  
  - clear use of Markdown/R Markdown,  
  - meaningful and rich history of commit messages,  
  - etc. 

- **Coding Style (10%)**:  
  - adherence to [R code conventions](http://adv-r.had.co.nz/Style.html),  
  - clarity for others reading your code,  
  - appropriate comments (neither too few nor too many),  
  - logical organization,  
  - use of descriptive variable names.  
  - see [Why Coding Style Matters](https://www.smashingmagazine.com/2012/10/why-coding-style-matters/).  

- **Resources and AI Narrative (10%)**: Evaluates  
  - proper citation of all external resources (links, page numbers, etc.),  
  - clear and honest AI narrative (if AI was used), written by you,  
  - reflection on what you learned.  

To achieve *Excellent* in a given category, all requirements described above must be met. For the other ratings, it might be that only one, or more than one, elements are missing. For example, you could achieve *Very Good* on “Coding Style” if you are following all coding conventions, but the code is inconsistent, or overly or under commented.

<!--
- **Coding Strategy (20%)**: evaluates the logic of your code (how it solves the problem); its correctness (whether it works or not); sophistication (depth of the solution); use of tools/techniques covered in-class (e.g., conditionals, functions, tidyverse); efficiency in minimizing repetitions.
- **Presentation and Explanation (20%)**: for assignments involving data visualization or presentation (tables, graphs, descriptive stats, data analyses), this evaluates the effectiveness of the graphic execution, the conceptual choices in presenting data, and your ability to interpret them. In all assignments, this category also assesses your proficiency with Markdown syntax.
- **Achievement (20%)**: evaluates your overall mastering of the concepts/tools required to complete the assignment (how well you understand them, your ability to deepen into them, etc.), your creativity, and ability to go above-and-beyond; an *"excellent"* in this category praises *outstanding* work produced in the assignment.
- **Reproducibility (20%)**: how well the assignment is in compliance with the course convention for reproducibility in this course - whether we can access your repo, whether all required elements are submitted, your use of Markdown and R Markdown, a rich history of informative commit messages, use of README, etc.
- **Coding Style (10%)**: pertains to stylistic issues, not to whether your code works. It evaluates how well the code follows the [R code conventions](http://adv-r.had.co.nz/Style.html) and how consistent it is. Examples include clarity of the code to read for a person who has not written it, use of comments (code should never be over-commented, nor under-commented), proper variables names, understandable/logical code organization, etc. See [here](https://www.smashingmagazine.com/2012/10/why-coding-style-matters/) for more and why this matters.
- **Recources and AI Narrative (10%)**: 
-->


### Grading Scheme

Your **final grade** is given by the cumulative score of all submitted work throughout the course. We use the following grading scheme to determine your final grade: A (95-100), A- (90-94), B+ (87-89), B (83-86), B- (80-82), C+ (77-79), C (73-76), C- (70-72). Grades below 70 are handled on a case-by-case basis.

**Pass/Fail:** If you plan to take this course as Pass/Fail, please email me to come up with a shared plan that aligns with your needs and the course expectations. A “Pass” in this course requires a minimum grade of C-. You can choose the Pass/Fail option at any time before the last assignment is graded and final grades are published.

**Regrades:** If we make mistakes, we will review any incorrect grading decisions. However, a few rules apply:

- Requests for regrades must be submitted in writing to the instructor with a detailed reason for why the given piece of work should be reassessed. Students are then required to meet with the professor to review and discuss the given piece of work. 
- Requests for regrades should be submitted no earlier than 24 hours after a graded piece of work is returned to you, and no later than one week. Before and after that time, we will not consider any requests for regrades, regardless of whether the regrade request is reasonable and justified.
- We will consider regrading requests where a grader made an actual mistake (e.g., they took points off, claiming you didn’t do something when you did do it, and the grader missed that when reading your submission). We will unlikely consider regrading requests that try to argue that we should not be taking points off for a given issue or your work has been graded too strictly.


### Deadlines and Late Submissions Policies

Deadlines can be found in the [course schedule](lectures/index.qmd). Specifically: 

- **Take-home assignments are due by 11:59 PM Chicago time:** Submit on Canvas the link to your GitHub repository. Each assignment includes a *24-hour grace period* during which late submissions will not incur a penalty. After this period, a penalty of 1 point will be deducted for every additional 24-hour period the assignment is late. No exceptions. *If the assignment is graded as Pass/Fail, no late submissions will be accepted* after the 24-hour grace period.

- **In-class Exams:** Students are expected to take the exams in class during the scheduled exam time. Make-up exams will be considered only in cases of *documented* circumstances beyond the student’s control (e.g., serious illness, medical or family emergency). Events like personal travel, work commitments, or undocumented issues do not qualify as valid reasons. All requests for a make-up exam must be submitted as soon as possible and in any case prior to the exam; otherwise the exam will be receive a 0. Approval is at the discretion of the instructor.

- **Oral Exam (optional):** The oral exam will be held in Week 10 and is optional. Students are responsible to sign-up for a slot and respect their sign-up time. Rescheduling requests will be considered only in cases of *documented* circumstances beyond the student’s control (e.g., serious illness, medical or family emergency) and approval is at the discretion of the instructor.


### Missed or Incomplete Submissions

Students are expected to submit all assignments in full and on time. Missed and incomplete submissions are treated as follows:  

- **Missed Submissions:** We expect students to submit all assignments. A missed assignment is worth 0 points (0%) and, as such, will affect your final grade. The course is designed with some built-in flexibility to accommodate unforeseen events or busier-than-normal weeks (e.g., 24-hour grace period on take-home work). Further exceptions will be unlikely, and will only be considered for truly exceptional and *documented* circumstances; you must contact the instructor prior to the assignment deadline, but please understand that an exception is not guaranteed. Things like starting an assignment late or having a busy week do not qualify as an exceptional circumstance. The built-in grace period is meant to give you some flexibility for such unexpected issues.

- **Incomplete Submissions:** For take-home assignments, if more than 25% of a submitted assignment is missing, that submission will not be graded and will be treated as a missed submission. If less than 25% is missing, the assignment will be graded with a penalty, depending on the assignment and the amount of it that is incomplete

<!--
#### Exams: Attendance and Expectations

Students are expected to take in-class exams during scheduled class time. 

Exams are closed-book: no notes, textbooks, phones, or other materials are permitted. Only the exam and your computer may be used. 

Make-up exams will be considered only in cases of *documented* circumstances beyond the student’s control (e.g., serious illness, medical or family emergency). Note: personal travel, work commitments, or undocumented issues do not qualify as valid reasons. All requests for a make-up exam must be submitted as soon as possible and prior to the exam. Approval is at the discretion of the instructor.
-->


## Academic Integrity & Use of AI

### Course-Specific Plagiarism and AI Policies

**Collaboration:** Collaboration is permitted, but direct copying of someone else's code is prohibited. Students in this course may help each other by answering questions, brainstorming approaches, and explaining concepts. We all benefit and learn from that. However, (a) you must acknowledge this in your assignment or work; and (b) each student must write, debug, and submit their own code: directly copying someone else's
code is prohibited.

**Use of External Resources:** External resources (e.g., beyond course readings, slides, and code shared in class) are permitted but only after having consulted course materials, and must be cited appropriately. If these resources are found online, copy and paste the link into your assignment; if offline (e.g., book, article), report the page or section; if AI was used, explain which tools you used and how (but see below on AI-specific policies). You are responsible for reporting the sources you consulted and for being able to explain any code or ideas incorporated from these sources.

<!--
Idea: Use pool everywhere to pool students first on these questions. Discuss, then release this course AI policy and talk about it and why. 
Question 1; What concerns do you have about AI usage in the classroom or assignments?
Question 2: What excited you about AI usage in the classroom or assignments?
Question 3: Do you think AI should be allowed or banned in completing assigments?
-->

**Use of LLMs and AI:** AI tools are powerful, accessible, and increasingly good at writing code. At this point, I am confident that AI tools can solve most of the assignments in this course. But this is a foundational course, and building a programming foundation is work you need to do yourself. The goal is to learn how to think through problems, make mistakes, revise, and understand why your code works or does not. If AI does too much work for you, you may finish the assignment, but you will miss out on much of the learning, as well as the satisfaction that comes from solving coding problems yourself.

For these reasons, AI use (e.g., ChatGPT, Copilot, Claude, etc.) in this course, must follow the guideliens below:

- *First try on your own.* Do not copy/paste prompts into AI to get preliminary solutions. You may consult AI for targeted help after at least 15 minutes of independent effort and reviewing class materials.
- *Use only class content and materials.* Your primary solution must use approaches taught in class (mainly slides and in-class code). Alternative solutions may be included, and even encouraged, but as additional work, properly cited, and compared against your primary solution.
- *Disclose use.* Every assignment must include a statement, written exclusively by you (no AI-editing, etc.), describing how (if at all) you used AI, for which task, and what you learned in the process.
- *Do not use AI in class.* Use of AI during in-class sessions is prohibited, unless explicitly asked/authorized by the instructor. At times, we may incorporate AI examples or exercises in class as part of building AI literacy and understanding appropriate use.

Any use of AI outside these conditions is considered an academic integrity violation and will receive zero credit. Examples include: submitting code written mainly by AI, submitting code not introduced in class as your primary solution (even if it works), failing to cite sources, omitting an AI disclosure narrative.

The bottom line: You must be the author of all work submitted. If you don’t understand what the program is doing and are not prepared to explain it, you should not submit it.


### UChicago Academic Integrity Policy

Each student in this course is expected to abide by the [University of Chicago Code of Academic Integrity](https://college.uchicago.edu/student-services/academic-integrity-student-conduct). Under the provisions of the Code, anyone who gives or receives unauthorized assistance in the preparation of work at home or during tests in class will be subject to disciplinary action. A student’s name on any piece of work is our assurance that they have neither given nor received any unauthorized help in its preparation.


## Accessibility and Support

The University of Chicago is committed to diversity and rigorous inquiry from multiple perspectives. Services and reasonable accommodations are available to persons with temporary and permanent disabilities, to students with DACA or undocumented status, to students facing mental health or other personal challenges, and to students with other kinds of learning challenges. Please contact me if there are circumstances affecting your ability to participate in class.

If you have, or think you may have a disability, please contact Student Disability Services for a confidential discussion and for requesting accommodation: SDS. Once SDS approves your accommodation, it will be emailed to both you and me. Please follow up with me to discuss the necessary logistics of your accommodations. If you need immediate accommodation, please speak with me after class or send an email message to me and SDS.

Some resources include: [Office of Student Disability Services](https://disabilities.uchicago.edu/), [UChicago Student Wellness](https://wellness.uchicago.edu/), [Center for Identity and Inclusion](https://inclusion.uchicago.edu/).

