---
title: "Lecture 1: Course Logistics, R, Markdown"
date: 2026-09-28
summary: "Course Logistics, R, Markdown"
url_slides: 01-slides.qmd
url_code: css-materials/r-markdown
format: html
page-layout: full
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Info and Materials

* **Date**: {{< meta date >}}
* **Topics**: {{< meta summary >}}
* **Slides**: To be posted before class
* **Code**: To be posted before class

<!--
* **Slides**: [View Slides]({{< meta url_slides >}})
* **Code**: `usethis::use_course("{{< meta url_code >}}")`
-->


## Learning Objectives

- Recognize the basic features of the R programming language and RStudio
- Write and run simple R code
- Describe R Markdown and why it's useful
- Create and edit an R Markdown document


## Before Class

- Go to <https://github.com> and follow the instructions to create a free GitHub account, if you do not have one already. See [these tips](https://happygitwithr.com/github-acct) for your username
- Once you have created a GitHub account [submit your GitHub username here](https://forms.gle/5Ly3qb5geY9Pch5j7) we need this information, else you won't be able to access the assignments for this course
- Complete this [intro survey](https://forms.gle/w3wo7dxy2HtLk5AU7)
- Verify you can log in into [R Workbench](https://macss-r.uchicago.edu/) using your UChicago credentials. If you cannot, please contact me at <nardin@uchicago.edu> and include your UChicago NetID and email address


## Readings

Skim the readings before and/or after class to get the big picture, review them for assignments and exams:

- [R Markdown, R4DS](https://r4ds.had.co.nz/r-markdown.html)
- [R Markdown Cheatsheet](https://rmarkdown.rstudio.com/lesson-15.HTML)
