---
title: "Lecture 2: Git and GitHub with RStudio"
date: 2026-09-30
summary: "Intro to Git and GitHub with RStudio"
url_slides: 02-slides.qmd
#url_code: css-materials/git
format: html
page-layout: full
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Info and Materials

* **Date**: {{< meta date >}}
* **Topics**: {{< meta summary >}}
* **Slides**: To be posted before class
* **Code**: To be posted before class

<!-- 
* **Slides**: [View Slides]({{< meta url_slides >}})
* **Code**: No in-class code for this session
-->


## Learning Objectives

- Understand what Git is and why it's useful
- Create a Git repository in RStudio
- Connect your Git repository to GitHub
- Practice staging, committing, and pushing changes


## Before Class

- Complete the Lecture 1 "Before Class" activities, if you haven't already. To follow along today you must *(1) be able to log in to R Workbench and (2) have a GitHub account*. Please plan ahead: GitHub requires two-factor authentication (you can use an authentication app of your choice, or the university Duo system, but setup may require some time).  
- Review Lecture 1 with the goal of getting comfortable **using** Workbench/RStudio, the Console, R scripts, R Markdown, and downloading course materials: the goal is not to learn new code yet, but to practice using these interfaces and tools. Focus especially on R Markdown by completing the exercises from the repo we downloaded in class (no submission needed).


## Readings

- Chapter 1 of [Happy Git and GitHub for the useR](https://happygitwithr.com/big-picture)
- Read the [Software Setup](../setup/index.qmd) page. We'll go do this setup together in class today
