---
title: "Lecture 8: Tidy Data with tidyr; Regex with stringr"
date: 2026-10-21
summary: "Tidy Data with tidyr; Regex with stringr"
url_slides: 08-slides.qmd
url_code: css-materials/tidydata  # merge with or create two links css-materials/regular-expr
page-layout: full
draft: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Info and Materials

* **Date**: {{< meta date >}}
* **Topics**: {{< meta summary >}}
* **Slides**: To be posted before class
* **Code**: To be posted before class

<!--
* **Slides**: [View Slides]({{< meta url_slides >}})
* **Code**: `usethis::use_course("{{< meta url_code >}}")`
REMEMBER TO ADD REGEX TO THE REPO OR ADD LINKS TO THAT OTHER REPO AS WELL
-->


## Learning Objectives

#### Tidy Data

* Define the concept of tidy data and its characteristics
* Practice tidying data using `tidyr`

#### Regular Expressions

* Define Strings, Regular Expressions, and their uses
* Introduce `stringr`
* Practice using Regular Expressions in R to extract info from strings


## Readings

#### Tidy Data

* ["Chapter 5 Data tidying"](https://r4ds.hadley.nz/data-tidy) from "R for Data Science" 2nd Edition
* [tidyr Documentation](https://tidyr.tidyverse.org/)
* [tidyr Cheat Sheet](https://github.com/rstudio/cheatsheets/blob/main/tidyr.pdf)

#### Regular Expressions

* [Chapter 14 "Strings"](https://r4ds.ha
dley.nz/strings) in "R for Data Science" 2nd Edition (especially 14.4 "Extracting data from strings")
* [Chapter 17](https://bookdown.org/rdpeng/rprogdatascience/regular-expressions.html#the-stringr-package) from *R Programming for Data Science*. Focus on the `stringr()` section — that’s all we cover in class, but the full chapter is a good reference if you want more
* [`stringr()` documentation and cheatsheet](https://stringr.tidyverse.org/)