---
title: "Computing for the Social Sciences"
format:
  html:
    toc: false
    theme: cosmo
---

### Course Assignments Fall 2026

<div class="my-4"></div>

Assessment for this course consists of four assignments, one final project, two in-class exams, and an optional oral exam. 

The two exams will include a mix of multiple-choice and open-ended questions. They will be held in class and will be closed-book. The oral exam is optional and will be held in Week 10. It is subjected to specific eligibility and scoring rules, which will be shared during class.

**The assignments and the final project will appear on this page when available. Click the assignment title in the callout box below to access it:**

::: {.callout-important appearance="minimal"}

- [Homework 1](hw01.qmd) due Thursday, October 8 (11:59 PM Chicago Time)

<!--
- [Homework 2](hw02.qmd) due Thursday, July 2 (11:59 PM Chicago Time)
- [Homework 3](hw03.qmd) due Thursday, July 9 (11:59 PM Chicago Time)
- [Homework 4](hw04.qmd) due ~~Thursday, July 16~~ Friday, July 17 (11:59 PM Chicago Time)
- [Homework 5 Final Project](hw05-project.qmd) due Thursday, July 16 (11:59 PM Chicago Time)
-->

:::


### Further info:

- Check our [Course Schedule](../lectures/index.qmd) for open and due dates of all assignments.

- Refer to the [Syllabus](../syllabus.qmd) for assessment policies, including guidelines on late or missing submissions, grading rubric, AI policies, and more.

<!--
For the boot camp, I just followed the Web GUI instructions they list on their Quickstart (steps 1-6 are sufficient for what we do in our classes) and this automatically sets up all the permissions and infrastructure necessary to allow students to accept assignments via a similar workflow as GitHub classroom (click a link to accept the assignment, which creates a private repo in the course organization that TAs can grade and/or students can submit on Gradescope). For future iterations, it may be worth writing a CLI setup script (they also provide CLI access). Just note that you need to add students to your Classroom 50 roster before they are able to accept assignments. Thankfully, this is easy though -- you can upload a list of UChicago email addresses and students will receive a message inviting them to join the course organization/Classroom 50 roster (we do not need to know their GitHub usernames ahead of time).

One thing I didn't try in the boot camp was group assignments. It looks like the workflow will be slightly different from what it was in the past, though. From what I read, it looks like one student will need to accept an assignment for their group and then the others will need to be manually added by their group mate to the GitHub repo. Again, I haven't tested this, though.
-->